<a href="https://colab.research.google.com/github/ShambhaveeThakur/ML-Project-end-to-end/blob/main/ANN_implement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import tensorflow as tf

In [17]:
print (tf.__version__)

2.18.0

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
dataset = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Churn_Modelling.csv")
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [21]:
## divide into dependent and independent features
X=dataset.iloc[:,3:13]
y=dataset.iloc[:,13]

In [22]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [ ]:
y

In [23]:
#feature engineering
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [25]:
#concatenate these variables with dataframe
X=pd.concat([X,geography,gender],axis=1)

In [31]:
X = dataset.drop(['Geography', 'Gender','Surname'], axis=1)

In [32]:
X.head()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0

In [33]:
#Splitting dataset into training n test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [34]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [30]:
X_train

,RowNumber,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7389,7390,15676909,Mishin,667,34,5,0.00,2,1,0,163830.64,0
9275,9276,15749265,Carslaw,427,42,1,75681.52,1,1,1,57098.00,0
2995,2996,15582492,Moore,535,29,2,112367.34,1,1,0,185630.76,0
5316,5317,15780386,Ferri,654,40,5,105683.63,1,1,0,173617.09,0
356,357,15611759,Simmons,850,57,8,126776.30,2,1,1,132298.49,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9225,9226,15584928,Ugochukwutubelum,594,32,4,120074.97,2,1,1,162961.79,0
4859,4860,15647111,White,794,22,4,114440.24,1,1,1,107753.07,0
3264,3265,15574372,Hoolan,738,35,5,161274.05,2,1,0,181429.87,0
9845,9846,15664035,Parsons,590,38,9,0.00,2,1,1,148750.16,0
2732,2733,15592816,Udokamma,623,48,1,108076.33,1,1,0,118855.26,1

In [35]:
X_test

array([[ 1.52455906, -1.05516175, -0.55204276, ...,  0.9687384 ,
         1.61085707, -0.50624244],
       [-1.41233952, -0.51193473, -1.31490297, ..., -1.03227043,
         0.49587037,  1.97533814],
       [-0.89381929, -0.80237087,  0.57162971, ...,  0.9687384 ,
        -0.42478674, -0.50624244],
       ...,
       [ 1.57813948,  1.13257291, -0.74791227, ..., -1.03227043,
         0.71888467, -0.50624244],
       [-0.77559668,  1.34311575, -0.00566991, ...,  0.9687384 ,
        -1.54507805, -0.50624244],
       [ 0.58983992, -1.56467681, -0.79945688, ..., -1.03227043,
         1.61255917, -0.50624244]])

In [36]:
X_train.shape

(8000, 11)

In [37]:
# part 2- creating the ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU,PReLU,ELU,ReLU
from tensorflow.keras.layers import Dropout

In [38]:
#Lets initialize the ANN
classifier=Sequential()

In [39]:
## Adding the input layer
classifier.add(Dense(units=11,activation='relu'))

In [62]:
## adding the first input layer
classifier.add(Dense(units=7,activation='relu')) # can add dropout layer also

In [41]:
## adding the second input layer
classifier.add(Dense(units=6,activation='relu'))

In [42]:
## Adding the output layer
classifier.add(Dense(units=1,activation='sigmoid'))

In [48]:
classifier.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])# by default adam uses 0.1 learning rate

In [49]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [54]:
model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=10)# can use early stopping keras in case number of epochs is very high and keyboard interrupted

Epoch 1/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 1.0000 - loss: 1.4721e-10 - val_accuracy: 1.0000 - val_loss: 1.8314e-10
Epoch 2/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 1.0000 - loss: 1.6847e-10 - val_accuracy: 1.0000 - val_loss: 1.8325e-10
Epoch 3/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.6819e-10 - val_accuracy: 1.0000 - val_loss: 1.8335e-10
Epoch 4/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 1.0000 - loss: 1.7815e-10 - val_accuracy: 1.0000 - val_loss: 1.8344e-10
Epoch 5/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 1.0000 - loss: 1.6473e-10 - val_accuracy: 1.0000 - val_loss: 1.8353e-10
Epoch 6/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 1.0000 - loss: 1.6721e-10 - val_accuracy: 1.0000 - val_loss: 1.8362e-10
Epoch 7/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 1.0000 - loss: 1.5966e-10 - val_accuracy: 1.0000 - val_loss: 1.8371e-10
Epoch 8/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 1.0000 - loss: 1.5705e-10 - val_accuracy: 1.0000 - val_loss: 1.8380e-10
Epoch 9/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 1.0000 - loss: 1.6376e-10 - val_accuracy: 1.0000 - val_loss: 1.8389e-10
Epoch 10/10
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 1.0000 - loss: 1.8436e-10 - val_accuracy: 1.0000 - val_loss: 1.8398e-10

In [55]:
model_history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [56]:
# predicting and evaluating the model
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [58]:
# make the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1595,    0],
       [   0,  405]])

In [59]:
##calculate the accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
score

1.0

In [60]:
##get the weights
classifier.get_weights()

[array([[-8.47206116e-02,  2.31181569e-02, -1.68078244e-01,
         -5.23687243e-01, -5.80939114e-01,  6.78259909e-01,
         -7.03745335e-02,  7.23327696e-03,  4.53077853e-02,
         -3.15194517e-01,  2.45815311e-02],
        [ 2.18286179e-02, -4.04538631e-01,  1.82101056e-01,
          3.57247256e-02,  3.96853201e-02,  6.75153077e-01,
         -5.17801106e-01,  2.37374380e-02, -1.08726747e-01,
         -1.58312902e-01, -2.50512928e-01],
        [ 1.06372662e-01,  7.65839368e-02, -3.46174091e-01,
         -7.54253790e-02,  4.92296487e-01, -6.95985630e-02,
         -1.01617664e-01,  1.35402024e-01, -9.22719166e-02,
         -2.03531504e-01,  2.51360655e-01],
        [-8.21425521e-04,  1.58407852e-01,  3.99315536e-01,
         -5.08961976e-01,  4.18160796e-01,  2.99236387e-01,
         -3.54213983e-01, -2.96361268e-01,  1.56388611e-01,
         -6.32746518e-02, -5.49798369e-01],
        [ 4.60805837e-03, -1.48936167e-01, -1.23779505e-01,
          3.12880039e-01, -1.66610360e-01,  1.18303441e-01,
         -5.51294088e-01, -1.67230368e-01,  1.38178334e-01,
         -2.64029741e-01,  4.65794235e-01],
        [-1.07745275e-01, -3.26149128e-02,  2.48439565e-01,
         -5.45760281e-02,  2.40265444e-01,  1.99163109e-02,
          2.62946099e-01,  1.99687555e-01,  3.73483717e-01,
         -2.59760827e-01,  4.39798266e-01],
        [-1.83768541e-01, -1.20647408e-01, -5.89558482e-01,
          2.64968246e-01,  1.03356063e-01,  1.89452991e-01,
         -1.68606445e-01,  1.05458140e-01,  2.52345234e-01,
         -5.22414207e-01, -1.47205874e-01],
        [-4.89017926e-03,  1.42530054e-01,  2.89722890e-01,
         -2.90147841e-01,  4.78040762e-02, -6.10048138e-03,
          4.53500688e-01,  2.02475011e-01,  3.11043859e-03,
          1.47538960e-01, -3.53284001e-01],
        [-9.07589421e-02,  2.68370777e-01,  1.23955831e-02,
         -1.32601529e-01,  2.86559582e-01, -3.94143701e-01,
          4.47333336e-01,  3.14340949e-01,  7.21990615e-02,
          2.86800444e-01,  5.04002929e-01],
        [-1.26355127e-01,  1.26302047e-02,  1.22754969e-01,
         -2.46465519e-01,  5.44028521e-01,  8.50584432e-02,
          3.33416820e-01, -6.99982746e-03,  2.34176531e-01,
          6.87464923e-02,  1.68157294e-01],
        [ 1.26796949e+00, -7.48487353e-01,  1.24745652e-01,
         -8.16945791e-01, -6.18940499e-03, -8.98765743e-01,
         -3.59773725e-01,  1.97546512e-01,  9.86540616e-01,
         -4.46661524e-02, -1.33519217e-01]], dtype=float32),
 array([ 0.22844978,  0.53927857,  0.07716249,  0.57854104,  0.11185823,
         0.68174994,  0.24658121, -0.44650823,  0.15760753, -0.19313993,
         0.11789804], dtype=float32),
 array([[ 1.1618673 ,  0.04705148,  0.86761534,  0.31562445, -0.15025209,
         -0.5838219 , -0.43615368],
        [-0.6909602 ,  0.2737511 ,  0.3037294 ,  1.0158184 ,  0.6960367 ,
          0.5440693 ,  0.4248156 ],
        [ 0.09553412,  0.4034207 ,  0.4448692 ,  0.62602925,  0.0424619 ,
         -0.20727953,  0.41351208],
        [-0.27925923, -0.5353627 , -0.4252705 ,  0.59216017,  0.5009389 ,
          0.37985748,  0.7735819 ],
        [ 0.01833927,  0.43717796, -0.36744204,  0.5350031 ,  0.21236566,
         -0.3792805 ,  0.09410408],
        [ 0.0252469 , -0.41625905, -0.05088699,  0.92417896,  0.65213346,
          0.3260664 ,  0.21770701],
        [ 0.2666434 , -0.51608   , -0.48328158,  0.02290475,  0.10278557,
          0.53902537,  0.43683547],
        [-0.03331552,  0.32271147,  0.11246042, -0.27376547, -0.2820714 ,
         -0.44023493, -0.00393003],
        [ 0.9292658 ,  0.27783495,  0.65259945, -0.1253928 , -0.70062834,
         -0.22344892, -0.34939238],
        [ 0.3546653 ,  0.21513058, -0.01019695,  0.20712541, -0.01307312,
          0.2002694 ,  0.25634953],
        [-0.16641858, -0.48430687, -0.06049702, -0.005527  ,  0.4678088 ,
          0.02310384,  0.10387402]], dtype=float32),
 array([ 0.0763159 , -0.09654612,  0.11746803,  0.622999  ,  0.53606516,
         0.4792224 ,  0.41592485], dtype=float32),
 array([[ 0.630747  , -0.4577051 ,  0.7191031 , -0.51333845, -0.16664118,
          1.1174963 ],
        [ 0.32408324,  0.15517962, -0.03888118,  0.28732964, -0.5077033 ,
          0.32081446],
        [-0.02816735, -0.30286613,  1.2326152 , -0.07923087, -0.30516863,
          0.7479365 ],
        [ 0.5618313 ,  0.94087595,  0.05978561,  0.9863524 ,  0.6597611 ,
          0.3635268 ],
        [-0.85984045,  0.40591738, -0.4795951 ,  1.2145473 ,  0.60739183,
         -0.65317696],
        [ 0.12487758,  1.1106032 , -0.32840714,  0.19325423,  0.72221243,
         -0.6410555 ],
        [-0.08115938,  0.75918555, -0.01022991,  0.45861942,  0.63209903,
         -0.47659394]], dtype=float32),
 array([-0.01281758,  0.40067086,  0.17016518,  0.28035945,  0.28053626,
         0.55393714], dtype=float32),
 array([[ 0.7830514],
        [-0.9986015],
        [ 1.1439503],
        [-1.1030667],
        [-1.300874 ],
        [ 0.7526543]], dtype=float32),
 array([-0.07662417], dtype=float32)]